version: '3.5'

services: 
    lease-service:
        image: sneyd321/lease-service
       
        ports: 
            - 8090:8090
        volumes:    
            - ./lease-service:/usr/src/app 

        restart: on-failure


    
        