apiVersion: apps/v1
kind: Deployment
metadata:
  name: lease-service
spec:
  selector:
    matchLabels:
      run: lease-service
  replicas: 1
  template:
    metadata:
      labels:
        run: lease-service
    spec:
      containers:
      - name: lease-service
        image: sneyd321/lease-service
        ports:
        - containerPort: 8090
        
      imagePullSecrets:
        - name: key